### ISSUE TITLE
Sync fretboard to MIDI

### ISSUE THREAD

**Issue by amorriscode** [amorriscode/terminal-hero#2]
We need the fretboard/notes to sync to the MIDI file so it feels like you're really playing.

- [ ] Separate fretboard notes into separate "strings" #10 
- [ ] Create a generic method of feeding an input of notes into the fretboard rendering #11 
- [ ] Hook up MIDI output to fretboard notes #12 
- [ ] Investigate how to stream buffer of MIDI (or pre-buffer it all) while also playing back audio files in sync #13

**Comment by amorriscode** [comment]
- https://github.com/ideoforms/isobar/blob/a65f78f9b827006e159436a1b1d3154896cfdd87/isobar/io/midifile/input.py
  - Parsing MIDI and making notes time based?
- https://github.com/YatingMusic/miditoolkit
  - I feel like this might come in handy or [some of the projects under Philosophy](https://github.com/YatingMusic/miditoolkit#philosophy)
  - Has visualization tools which can be used directly or for inspiration

**Comment by hyshka** [comment]
In the first link, that's really interesting that they computed note duration.

The other libraries are good finds as well. Good to know others use different timing methods.
